### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/tasks/shared/Css'

### ISSUE THREAD

**Issue by xmoki** [JeffreyWay/laravel-elixir-stylus#19]
Something must have changed on laravel-elixir 6 that broke laravel-elixir-stylus, the error below happens if using laravel-elixir@^6.0.0-1 but not when using 5.0.0 or below.

vagrant@homestead:/srv/www/vue$ gulp
module.js:341
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/tasks/shared/Css'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-elixir-stylus/index.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by abstractFlo** [comment]
Same Error on 6.0.0-2
