### ISSUE TITLE
gulp woks fine but if I install your stylus package gulp throws error

### ISSUE THREAD

**Issue by zartosht** [JeffreyWay/laravel-elixir-stylus#22]
Hi,
I don't know what happend but the fresh install of laravel, gulp woks fine but if I install your stylus package gulp throws this error:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/dist/tasks/CssTask'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/PATH_TO_LARAVEL/node_modules/laravel-elixir-stylus/index.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

**Comment by JeffreyWay** [comment]
You're pulling in the wrong version. See the readme notes.
