### ISSUE TITLE
Cannot find module 'laravel-elixir/ingredients/helpers/Utilities'

### ISSUE THREAD

**Issue by jakecleary** [JeffreyWay/laravel-elixir-stylus#6]
Hi,

When running `laravel-elixir` with the `laravel-elixir-stylus` package, I get the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'laravel-elixir/ingredients/helpers/Utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jakecleary/pp/touchline/node_modules/laravel-elixir-stylus/index.js:8:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

My gulp file looks like this:

```js
var elixir = require('laravel-elixir');

require('laravel-elixir-stylus');

elixir(function(mix) {
    mix.stylus('main.styl');
});
```

My stylus file is here: `/resources/assets/stylus/main.styl`

Any help would be greatly appreciated. Thank you in advance :smile:

**Comment by J5lx** [comment]
Same here. The cause should be [cb1f7c5b676870460a4e1ffb8e79a6a4bb16d114](https://github.com/laravel/elixir/commit/cb1f7c5b676870460a4e1ffb8e79a6a4bb16d114) in laravel/elixir.

**Comment by jholl** [comment]
changing the index.js to `/commands/` instead of `/helpers/` fixed it.

**Comment by jakecleary** [comment]
Thanks @jholl, will give this a go!

**Comment by Pravinslk** [comment]
@jholl which index,js file im also getting same error Laravel 5.2??

**Comment by matrunchyk** [comment]
Laravel 5.2. Same error

**Comment by JeffreyWay** [comment]
Make sure you're using the proper version of this package. See the readme.
